### ISSUE TITLE
Wheel can only spin once

### ISSUE THREAD

**Issue by CodeSpent** [joffreyBerrier/vue-fortune-wheel#11]
**Describe the bug**
Wheel is incapable of spinning more than once.

**To Reproduce**
1. Click wheel to spin
2. Try to click & spin again

Wheel will not spin again.

**Expected behavior**
Wheel spins as many times as desired.

**Comment by willans** [comment]
Looks like the value of `data.clicked` needs resetting back to false after the spin is done.

**Comment by CodeAddictx10** [comment]
I found a solution add :key to the component and update the key beforeUpdate

 <Wheel
     :key="key"
 />
 
 
  beforeUpdate() {
        this.key = Math.floor(Math.random() * 50) + 1;
    },

**Comment by l3luesmile** [comment]
i do this
`done(){ 
this.$refs.wheel.clicked = false;
}`

**Comment by joffreyBerrier** [comment]
Hi :)
https://github.com/joffreyBerrier/vue-fortune-wheel/blob/main/README.md#how-to-launch-the-wheel-
