### ISSUE TITLE
Failed to resolve entry for package "vue3-fortune-wheel"

### ISSUE THREAD

**Issue by daaanny90** [joffreyBerrier/vue-fortune-wheel#15]
**Describe the bug**
By building a project with vue-fortune-wheel as a dependency, I get the following error
`[vite:resolve] Failed to resolve entry for package "vue3-fortune-wheel". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue3-fortune-wheel".`

**To Reproduce**
1. Install vue3-fortune-wheel as a dependency for a project
2. Run `npm install`
3. Run `npm run build`

**Expected behavior**
A Build without errors

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Project made with Vite version 2.9.9
 - Node version 16.8

**Additional context**
I looked directly under `node-modules` and in the `vue3-fortune-wheel` folder, in the `package.json` under `module` and `exports` there is a reference to a file that actually does not exsists under `dist`: `vue3-fortune-wheel.es.js`

**Comment by AhmedKhchai** [comment]
Having the same error after I `npm run serve` the project after installing and using the package.

**Comment by joffreyBerrier** [comment]
Hi, @AhmedKhchai and @daaanny90  I have solved the problem, sorry for that!
I have created an example folder that use the last version and its works
I still have problems with typescript but I check that this week sorry!

Use the lasted version : `1.1.35`

**Comment by AhmedKhchai** [comment]
Hello, Thank you @joffreyBerrier ! Good luck !
