### ISSUE TITLE
Missing library.css

### ISSUE THREAD

**Issue by cjpitch23** [joffreyBerrier/vue-fortune-wheel#18]
**Describe the bug**
It seems that the latest version is missing the library.css that the package depends on.

**To Reproduce**
1. Create a new vue project
2. Install the latest version of 'vue-fortune-wheel'
3. Try to run the application

**Expected behavior**
After following the documentation, the wheel should load on the webpage, but it is unable to due to the missing css.

**Screenshots**
![image](https://user-images.githubusercontent.com/26605220/197824992-47b449cb-1e99-40ed-a08d-8726771368ef.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome

**Comment by joffreyBerrier** [comment]
It's fixed use the last version
