### ISSUE TITLE
How can I remove the big white cirle at the center.

### ISSUE THREAD

**Issue by Fasikawkn** [joffreyBerrier/vue-fortune-wheel#21]
I tried to customize it but I am unable to do so.

I want to remove the big white cirle at the center. 
And I want the indicator to start at one of the slice in the beginning. how can I achieve these?

**Comment by javadgholipoor** [comment]
document.querySelectorAll('.wheelholder circle')[0].remove()

**Comment by joffreyBerrier** [comment]
Hi @Fasikawkn sorry for the delay :D you can just pass the props `middle-circle` to `false`, do not used Javascript dom selector

**Comment by joffreyBerrier** [comment]
Hi @Fasikawkn sorry for the delay :D you can just pass the props `middle-circle` to `false`, do not used Javascript dom selector using new version **2.0.0**
